// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcmean
NumericVector rcmean(NumericMatrix x, int margin);
RcppExport SEXP lasso_poisson_rcmean(SEXP xSEXP, SEXP marginSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type margin(marginSEXP);
    rcpp_result_gen = Rcpp::wrap(rcmean(x, margin));
    return rcpp_result_gen;
END_RCPP
}
// rcsum
NumericVector rcsum(NumericMatrix x, int margin);
RcppExport SEXP lasso_poisson_rcsum(SEXP xSEXP, SEXP marginSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type margin(marginSEXP);
    rcpp_result_gen = Rcpp::wrap(rcsum(x, margin));
    return rcpp_result_gen;
END_RCPP
}
// stdC
double stdC(NumericVector x);
RcppExport SEXP lasso_poisson_stdC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(stdC(x));
    return rcpp_result_gen;
END_RCPP
}
// standardizeC
NumericVector standardizeC(NumericVector x);
RcppExport SEXP lasso_poisson_standardizeC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(standardizeC(x));
    return rcpp_result_gen;
END_RCPP
}
// rcstdC
NumericVector rcstdC(NumericMatrix x, int margin);
RcppExport SEXP lasso_poisson_rcstdC(SEXP xSEXP, SEXP marginSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type margin(marginSEXP);
    rcpp_result_gen = Rcpp::wrap(rcstdC(x, margin));
    return rcpp_result_gen;
END_RCPP
}
// SC
double SC(double z, double r);
RcppExport SEXP lasso_poisson_SC(SEXP zSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(SC(z, r));
    return rcpp_result_gen;
END_RCPP
}
// mat_vec
NumericVector mat_vec(NumericMatrix X, NumericVector y);
RcppExport SEXP lasso_poisson_mat_vec(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(mat_vec(X, y));
    return rcpp_result_gen;
END_RCPP
}
// lasso_poisson_singleC
NumericVector lasso_poisson_singleC(NumericMatrix X, NumericVector y, double lambda, NumericVector beta_ini, int max_iter, double tol);
RcppExport SEXP lasso_poisson_lasso_poisson_singleC(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP beta_iniSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_ini(beta_iniSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(lasso_poisson_singleC(X, y, lambda, beta_ini, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
