# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcmean <- function(x, margin) {
    .Call('lasso_poisson_rcmean', PACKAGE = 'lasso.poisson', x, margin)
}

rcsum <- function(x, margin) {
    .Call('lasso_poisson_rcsum', PACKAGE = 'lasso.poisson', x, margin)
}

stdC <- function(x) {
    .Call('lasso_poisson_stdC', PACKAGE = 'lasso.poisson', x)
}

standardizeC <- function(x) {
    .Call('lasso_poisson_standardizeC', PACKAGE = 'lasso.poisson', x)
}

rcstdC <- function(x, margin) {
    .Call('lasso_poisson_rcstdC', PACKAGE = 'lasso.poisson', x, margin)
}

SC <- function(z, r) {
    .Call('lasso_poisson_SC', PACKAGE = 'lasso.poisson', z, r)
}

mat_vec <- function(X, y) {
    .Call('lasso_poisson_mat_vec', PACKAGE = 'lasso.poisson', X, y)
}

lasso_poisson_singleC <- function(X, y, lambda = 0, beta_ini = 0L, max_iter = 300L, tol = 1e-7) {
    .Call('lasso_poisson_lasso_poisson_singleC', PACKAGE = 'lasso.poisson', X, y, lambda, beta_ini, max_iter, tol)
}

